// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MortgageComparer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MortgageComparer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223133332_NewEntities")]
    partial class NewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MortgageComparer.Entities.JobTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.PersonalDocumentTypeEntitycs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonalDocumentType");
                });

            modelBuilder.Entity("MortgageComparer.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("JobTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MortgageComparer.Entities.UserEntity", b =>
                {
                    b.HasOne("MortgageComparer.Entities.JobTypeEntity", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId");

                    b.HasOne("MortgageComparer.Entities.PersonalDocumentTypeEntitycs", "PersonalDocumentType")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.OwnsOne("MortgageComparer.Models.JobDetailsModel", "JobDetails", b1 =>
                        {
                            b1.Property<int>("UserEntityId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("JobTypeId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");

                            b1.OwnsOne("MortgageComparer.Models.MoneyModel", "IncomeAmount", b2 =>
                                {
                                    b2.Property<int>("JobDetailsModelUserEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnType("varchar(3)");

                                    b2.HasKey("JobDetailsModelUserEntityId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("JobDetailsModelUserEntityId");
                                });

                            b1.Navigation("IncomeAmount")
                                .IsRequired();
                        });

                    b.OwnsOne("MortgageComparer.Models.PersonalDocumentModel", "PersonalDocument", b1 =>
                        {
                            b1.Property<int>("UserEntityId")
                                .HasColumnType("integer");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("TypeId")
                                .HasColumnType("integer");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("JobDetails");

                    b.Navigation("JobType");

                    b.Navigation("PersonalDocument");

                    b.Navigation("PersonalDocumentType");
                });
#pragma warning restore 612, 618
        }
    }
}
