// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MortgageComparer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MortgageComparer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110181748_AddedContractToDatbase")]
    partial class AddedContractToDatbase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MortgageComparer.Entities.JobTypeEntity", b =>
                {
                    b.Property<int>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.OfferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("BankPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("Contract")
                        .HasColumnType("text");

                    b.Property<byte[]>("ContractData")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ContractLinkValidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalBankOfferId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<string>("SingedBy")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("MortgageComparer.Entities.PersonalDocumentTypeEntity", b =>
                {
                    b.Property<int>("PersonalDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonalDocumentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonalDocumentId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Income")
                        .HasColumnType("integer");

                    b.Property<string>("IncomeCurrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JobEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JobStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JobTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MortgageComparer.Entities.OfferEntity", b =>
                {
                    b.HasOne("MortgageComparer.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MortgageComparer.Models.MoneyModel", "MonthlyInstallment", b1 =>
                        {
                            b1.Property<int>("OfferEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("varchar(3)");

                            b1.HasKey("OfferEntityId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferEntityId");
                        });

                    b.OwnsOne("MortgageComparer.Models.MoneyModel", "RequestedMoney", b1 =>
                        {
                            b1.Property<int>("OfferEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("varchar(3)");

                            b1.HasKey("OfferEntityId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferEntityId");
                        });

                    b.Navigation("MonthlyInstallment");

                    b.Navigation("RequestedMoney")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MortgageComparer.Entities.UserEntity", b =>
                {
                    b.HasOne("MortgageComparer.Entities.PersonalDocumentTypeEntity", "PersonalDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("MortgageComparer.Entities.JobTypeEntity", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId");

                    b.Navigation("JobType");

                    b.Navigation("PersonalDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
