// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MortgageComparer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MortgageComparer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124185916_fixMigration")]
    partial class fixMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MortgageComparer.Entities.ApiOfferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Contract")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ContractData")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ContractLinkValidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentLink")
                        .HasColumnType("text");

                    b.Property<int>("MonthlyInstallementAmount")
                        .HasColumnType("integer");

                    b.Property<string>("MonthlyInstallementCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedAmount")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestedPeriodInMonths")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SignedContract")
                        .HasColumnType("bytea");

                    b.Property<string>("SingedBy")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("UserId");

                    b.ToTable("OurApiOffers");
                });

            modelBuilder.Entity("MortgageComparer.Entities.ApiUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("text");

                    b.Property<int?>("DocTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "jobEndDate");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("JobTypeId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "typeId");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "jobStartDate");

                    b.HasKey("Id");

                    b.ToTable("OurApiUsers");
                });

            modelBuilder.Entity("MortgageComparer.Entities.JobTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.OfferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("BankPercentage")
                        .HasColumnType("double precision");

                    b.Property<byte[]>("ContractData")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ContractLinkValidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentLink")
                        .HasColumnType("text");

                    b.Property<string>("ExternalBankOfferId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<string>("SingedBy")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("UserId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("MortgageComparer.Entities.PersonalDocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.QuoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExternalQuoteId")
                        .HasColumnType("integer");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Income")
                        .HasColumnType("integer");

                    b.Property<string>("IncomeCurrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JobEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JobStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JobTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MortgageComparer.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountToPay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<int>("InstalmentRate")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OurApiQuotes");
                });

            modelBuilder.Entity("MortgageComparer.Entities.ApiOfferEntity", b =>
                {
                    b.HasOne("MortgageComparer.Entities.QuoteEntity", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MortgageComparer.Entities.ApiUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MortgageComparer.Entities.ApiUserEntity", b =>
                {
                    b.OwnsOne("MortgageComparer.Models.MoneyDto", "Income", b1 =>
                        {
                            b1.Property<int>("ApiUserEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("varchar(3)");

                            b1.HasKey("ApiUserEntityId");

                            b1.ToTable("OurApiUsers");

                            b1.WithOwner()
                                .HasForeignKey("ApiUserEntityId");
                        });

                    b.Navigation("Income");
                });

            modelBuilder.Entity("MortgageComparer.Entities.OfferEntity", b =>
                {
                    b.HasOne("MortgageComparer.Entities.QuoteEntity", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MortgageComparer.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MortgageComparer.Models.MoneyDto", "MonthlyInstallment", b1 =>
                        {
                            b1.Property<int>("OfferEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("varchar(3)");

                            b1.HasKey("OfferEntityId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferEntityId");
                        });

                    b.OwnsOne("MortgageComparer.Models.MoneyDto", "RequestedMoney", b1 =>
                        {
                            b1.Property<int>("OfferEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("varchar(3)");

                            b1.HasKey("OfferEntityId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferEntityId");
                        });

                    b.Navigation("MonthlyInstallment");

                    b.Navigation("Quote");

                    b.Navigation("RequestedMoney");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MortgageComparer.Entities.QuoteEntity", b =>
                {
                    b.OwnsOne("MortgageComparer.Models.MoneyDto", "InstalmentAmount", b1 =>
                        {
                            b1.Property<int>("QuoteEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("varchar(3)");

                            b1.HasKey("QuoteEntityId");

                            b1.ToTable("Quotes");

                            b1.WithOwner()
                                .HasForeignKey("QuoteEntityId");
                        });

                    b.Navigation("InstalmentAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("MortgageComparer.Entities.UserEntity", b =>
                {
                    b.HasOne("MortgageComparer.Entities.PersonalDocumentTypeEntity", "PersonalDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("MortgageComparer.Entities.JobTypeEntity", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId");

                    b.Navigation("JobType");

                    b.Navigation("PersonalDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
